name: Tests
on: [pull_request]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby
        with:
          ruby-version: 3.0.0
      - name: Setup RSpec
        run: |
          [ -f Gemfile ] && bundle
          gem install --no-document rspec -v '>=3.0, < 4.0'
      - name: RSpec Report
        run: rspec --force-color --format documentation